spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes